# This is a basic workflow to help you get started with Actions

name: run the workflow

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Build and Deploy to Sandbox"]
    types:
      - completed
      
  repository_dispatch:
    types: [my-event, my-event1, my-event2]

jobs:
  build:
    name: run-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
#       - name: Download artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: my-app
#           path: artifacts/my-app.jar
      
    
      - uses: actions/download-artifact@master
        with:
          name: artifacts
          path: artifacts.jar
          
      - name: List downloaded artifact
        run: |
          ls target/
          ls target/*.jar
          
      - name: print trigger details
        run: |
          echo ${{ github.event.client_payload.github.action }}
          echo ${{ github.event.client_payload.github.actor }}
