name: Test Private Repo

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest release
        id: latest_release
        uses: gr2m/get-latest-release@v1
        with:
          owner: Mayureshgithub
          repo: Test_private_repo

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: .
