name: Test Workflow

on:
  repository_dispatch:
    types: [test-workflow]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: test
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: .
      - name: Test
        run: |
          ls -lrta 
          # test commands here
