name: Test Workflow

on:
  workflow_dispatch:
  push:
   branches: [ convictional-2 ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           repository: Mayureshgithub/upload_artifact_private_repository
           ref: ${{ github.event.release.tag_name }}
           token: ${{ secrets.PAT_TOKEN_TEST }}
           
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: .
       
      - name: Test
        run: |
          ls -lrta 
          # test commands here

#    deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download build artifacts
#         uses: actions/download-artifact@v2
#         with:
#           name: build-artifacts
#           repository: owner/repo-name   # Replace with the owner and repository name where the artifacts were uploaded
#           path: .
