# name: Test Workflow

# on:
#   workflow_dispatch:
#   push:
#    branches: [ convictional-2 ]
   
   

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#            repository: Mayureshgithub/upload_artifact_private_repository
#            ref: ${{ github.event.release.tag_name }}
#            token: ${{ secrets.PAT_TOKEN_TEST }}
           
# #       - name: Download build artifacts
# #         uses: actions/download-artifact@v2
# #         with:
# #           name: build-artifacts
# #           path: .
       
#       - name: Test
#         run: |
#           ls -lrta 
#           # test commands here
          
#       - name: List artifact
#         run: |
#           curl -L \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.PAT_TOKEN_TEST }}"\
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             https://api.github.com/repos/Mayureshgithub/upload_artifact_private_repository/actions/artifacts
            
#       - name: Test
#         run: |
#           pwd
#           ls -lrta 
          
          
          

#    deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download build artifacts
#         uses: actions/download-artifact@v2
#         with:
#           name: build-artifacts
#           repository: owner/repo-name   # Replace with the owner and repository name where the artifacts were uploaded
#           path: .


name: Download Latest Artifact

on:
  push:
   branches: [ convictional-2 ]
  workflow_dispatch:

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Download Latest Artifact
        id: download-artifact
        env:
          TOKEN: ${{ secrets.PAT_TOKEN_TEST }}
        run: |
          # Get the latest workflow run ID
          RUN_ID=$(curl -s -X GET -H "Accept: application/vnd.github+json" -H "Authorization: Bearer  ${{ secrets.PAT_TOKEN_TEST }}" "https://api.github.com/reposMayureshgithub/upload_artifact_private_repository/actions/runs?status=success&per_page=1" | jq -r '.workflow_runs[0].id')

          # Get the latest artifact ID
          ARTIFACT_ID=$(curl -s -X GET -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PAT_TOKEN_TEST }}" "https://api.github.com/repos/Mayureshgithub/upload_artifact_private_repository/actions/runs/$RUN_ID/artifacts" | jq -r '.artifacts[0].id')

          # Get the latest artifact URL
          ARTIFACT_URL=$(curl -s -X GET -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PAT_TOKEN_TEST }}" "https://api.github.com/repos/Mayureshgithub/upload_artifact_private_repository/actions/artifacts/$ARTIFACT_ID" | jq -r '.archive_download_url')

          # Download the artifact
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PAT_TOKEN_TEST }}" -H "X-GitHub-Api-Version: 2022-11-28" $ARTIFACT_URL --output build-artifacts.zip

      - name: Display output
        run: |
          echo "Artifact downloaded:  build-artifacts.zip"
          
      - name: Test
        run: |
          pwd
          ls -lrta    




